### ISSUE TITLE
Toggle not working for dimmers

### ISSUE THREAD

**Issue by JoryHogeveen** [kind3r/livolo-rf-codes#2]
Just tested with a switch. ON/OFF works fine but the Toggle option isn't recognized by the switch.
Should this be a different remote ID or something? What button code are you using for toggle?

**Comment by kind3r** [comment]
First remote ID is chosen randomly and stored on your browser (just like with the other settings) and you can see it in the advanced tab. Then it's incremented for each gang so that each gang has it's own remote ID for the ON / OFF scenes to work independently.

The button code for TOGGLE is BTN10

I have just tested my TOGGLEs (which I don't really use) and they do work but sometimes they trigger twice which means that I have set the repeat count for the code sent a bit too high (I did that cause sometimes ON/OFF scenes did not work). The original repeat count was 127 and I use 200.

I have now lowered the the repeat on the toggle to 127, can you check the new config (works fine for me now) ?

**Comment by JoryHogeveen** [comment]
Hello @kind3r 
Tried the new codes but unfortunately the new code isn't working yet.
I'm also not sure if TOGGLE is BTN10.
I have the touch remote and the way that works is simply by assigning a number (BTN1 for example) to a switch.
There is no BTN10 on that remote.

Touch remote codes:
1: 0,
2: 96,
3: 120,
4: 24,
5: 80,
6: 48,
7: 108,
8: 12,
9: 72;
10: 40,  << Cannot find this one on the remote.
OFF: 106
Scene 1 - 90
Scene 2 - 114
Scene 3 - 10
Scene 4 - 18

**Comment by kind3r** [comment]
I don't actually have a remote :) but the swithes learn the TOGGLE command just fine, just like any other button on any remote. Can you try re-learning the TOGGLE code on one of the switches ? Does the switch beep to confirm learning the code after you run the script (just like with the scenes) ? Trying to learn the same code twice will actually un-learn it.

**Comment by JoryHogeveen** [comment]
I already reset the dimmer-switch twice and tried to learn the TOGGLE code again. No beeps (the Broadlink RM Pro does indicate it's sending a signal).
Learning ON/OFF works fine.
I think this might be related to dimmer switches vs. normal switches.

**Comment by JoryHogeveen** [comment]
Ok just tried TOGGLE with a normal switch. Indeed, that works great!
This issue is related to dimmers only (#1)

**Comment by kind3r** [comment]
Since I don't have a dimmer it's not possible for me to test how they operate. It is possible that they don't register BTN10, I have changed TOGGLE to BNT1, can you test if that one registers and works on the dimmer ?
I will revert back this change after the test as all my switches have BTN10 assigned :) I will implement it for the dimmers only.

**Comment by JoryHogeveen** [comment]
Just tried it, still not working :(
The base64 code did change so I assume I have the correct one for BTN1:
Remote ID: `12871`
Code: `sn8mABMGBgYGDAwGBgYGDAYGBgYMBgYGBgYGDAwMBgYGBgYGBgYGBgYGBgYAAAAAAAAAAAAAAAAAAAAA`

There must be something else different. I'll do some more digging.

**Comment by kind3r** [comment]
Maybe they work with `68=70 - TOGGLE DIM (5 modes)`, I'll try to add that as toggle for dimmers only.

How does it work on the remote ? You assign the dimmer to button x and it toggles ? Or does it dim up and down while the button is pressed ?

**Comment by JoryHogeveen** [comment]
> How does it work on the remote ? You assign the dimmer to button x and it toggles ? Or does it dim up and down while the button is pressed ?

Indeed, you just assign the dimmer to a number on the remote and it toggles. Pressing and holding dims up and down.

Found this list on a thread: https://forum.arduino.cc/index.php?topic=153525.165#msg_3640617_quick_mod
```
If anyone is interested,here is the codes for my VL-RMT-04 touch remote


room 1                                     button

remoteID:26339 - key code:0          1
remoteID:26339 - key code:96        2
remoteID:26339 - key code:120      3
remoteID:26339 - key code:24        4
remoteID:26339 - key code:108      5
remoteID:26339 - key code:72        6
remoteID:26339 - key code:48        7
remoteID:26339 - key code:12        8
remoteID:26339 - key code:80        9
remoteID:26339 - key code:106      Alloff
remoteID:26339 - key code:90       scene1
remoteID:26339 - key code:114     scene2

dim
remoteID:26339 - key code:68        1
remoteID:26339 - key code:78        2
remoteID:26339 - key code:86        3
remoteID:26339 - key code:102      4
remoteID:26339 - key code:92        5
remoteID:26339 - key code:126      6
remoteID:26339 - key code:34        7
remoteID:26339 - key code:116      8
remoteID:26339 - key code:36        9
```

EDIT:
Not sure if the DIM codes are of any use as they probably only work when continuously sending that signal.

**Comment by JoryHogeveen** [comment]
Just tried to redo the HA config with that RemoteID and now it works. What BTN ID is it currently set on?

**Comment by kind3r** [comment]
> Just tried to redo the HA config with that RemoteID and now it works. What BTN ID is it currently set on?

Still on BTN1. So maybe there are only some remotes that work for dimmers ? Can you also try 7400 ? Also 18288 ?

**Comment by JoryHogeveen** [comment]
I think this is indeed RemoteID related.

7400 & 12871 didn't work > did work for regular switches (Using BTN 10)
18288 & 26339 worked for dimmers (Using BTN 1)

**Comment by kind3r** [comment]
```
12871 011001001000111 (7)
7400  001110011101000 (7)
18288 100011101110000 (7) *
26339 110011011100011 (9) *
```
Maybe remotes starting from `16384 100000000000000` work for dimmers also ?

**Comment by JoryHogeveen** [comment]
16384 Didn't work
16387 Didn't work
16389 Didn't work
For some reason the codes in between cannot be selected.

Went up a bit (below 18288)

18286 Worked!
18285 Worked!
...
18083 Worked!
...
17084 Worked!
...
16500 Worked!
...
16399 Worked!
...
16390 Didn't work

**Comment by kind3r** [comment]
So, there are 2 types of remotes, ones with 4 buttons and ones with many buttons :) (well now we know that the ones with many buttons are also 2 types, at least).
The ones with 4 buttons have an even number of 1's in their binary, which don't have scene buttons. 
The ones with many buttons have an odd number of 1's in their binary and have the scenes buttons we can use for always ON or OFF.

**Comment by JoryHogeveen** [comment]
Yep, and just tested `16396` and that didn't work. So for dimmers I ASSUME it should be `16399` or higher.

EDIT: Ok that isn't the case as well.. Just tried 55555 and that one didn't work..

**Comment by kind3r** [comment]
Could you try 16408, 26560, 26623, 32764 and 32767. I may be starting to find a pattern here.

**Comment by JoryHogeveen** [comment]
Definitely, I'll try them later tonight once I'm back home!

**Comment by kind3r** [comment]
PS: I rolled back to BTN10, but I guess it should also work with a valid remote ID

**Comment by kind3r** [comment]
> Indeed, you just assign the dimmer to a number on the remote and it toggles. Pressing and holding dims up and down.
> ...
> Not sure if the DIM codes are of any use as they probably only work when continuously sending that signal.

Just to understand if there would be any possible implementation of dimming, I assume let's say a full on using dimming takes 10 seconds and the light is off. Now, if I press and hold the button for 5 seconds it would turn on the light to 50%. What happens if I start pressing and holding the button again, does it continue form 50% towards 100% or does it dim towards 0%.
Cause if it goes from 0% to 100% and only after it reaches 100% it starts decreasing then this could be used in HA (by pressing the same button over and over to increment the brigthenss and decrement once it's at max). On the other hand if pressing and holding the button always changes the direction then yes, it's useless.

I could setup the 4 scenes available for different dimming values the way mentioned in #3 (you would have to dim to the preffered level and assign the scene to it), not impossible, but if you have many switches then it would be a pain :) It's easier to get some IKEA bulbs for the place where you want them dimmable.

**Comment by JoryHogeveen** [comment]
> What happens if I start pressing and holding the button again, does it continue form 50% towards 100% or does it dim towards 0%.

Dimming on my remote is like this:
Once you hold it down and it's at 0% it will go up until you stop or until it's at 100%. Once you hold it down again it will go down until you stop or it's at 0%. Hold it down again and the dimmer will to up.

These are different codes than scenes or DIM+ and DIM- (see dim codes here: https://github.com/kind3r/livolo-rf-codes/issues/2#issuecomment-572630659)

**Comment by JoryHogeveen** [comment]
> Could you try 16408, 26560, 26623, 32764 and 32767. I may be starting to find a pattern here.

All these codes didn't work for toggling dimmers.
Could be because you've set it back to BTN10 though...

**EDIT:**
It was indeed the BTN number. Used https://www.tyjtyj.com/livolo.php to generate the new base64 for BTN1 and all codes worked **EXCEPT 16408!**

I did notice that the tyjtyj didn't create the exact same base64 codes, is this because of the repeat count??
For example:
RemoteID `32767`
BTN10 with your app: `sn8mABMGBgwMDAwMDAwMDAwMDAwMDAYGDAYGDAYGBgYGBgAAAAAAAAAAAAA=`
BTN10 with tyjtyj: `soAmABMGBgwMDAwMDAwMDAwMDAwMDAYGDAYGDAYGBgYGBgAAAAAAAAAAAAA=`

**Comment by kind3r** [comment]
> Dimming on my remote is like this:
Once you hold it down and it's at 0% it will go up until you stop or until it's at 100%. Once you hold it down again it will go down until you stop or it's at 0%. Hold it down again and the dimmer will to up.

So implementing the button dimming codes does not make any sense as I don't think there is a way to implment this in HA.

> These are different codes than scenes or DIM+ and DIM- (see dim codes here: #2 (comment))

This would be an option via another remote ID, we would have to test for remote IDs also to see which ones support this.

> > Could you try 16408, 26560, 26623, 32764 and 32767. I may be starting to find a pattern here.
> 
> It was indeed the BTN number. Used https://www.tyjtyj.com/livolo.php to generate the new base64 for BTN1 and all codes worked **EXCEPT 16408!**
> 
Ok, so what I got so far:
- works for BTN1-9
- ID is between `16399` and `32767`
- ID binary value to have odd number of `1`'s 
- ID binary value to have at least 5 `1`'s

> I did notice that the tyjtyj didn't create the exact same base64 codes, is this because of the repeat count??
> For example:
> RemoteID `32767`
> BTN10 with your app: `sn8mABMGBgwMDAwMDAwMDAwMDAwMDAYGDAYGDAYGBgYGBgAAAAAAAAAAAAA=`
> BTN10 with tyjtyj: `soAmABMGBgwMDAwMDAwMDAwMDAwMDAYGDAYGDAYGBgYGBgAAAAAAAAAAAAA=`

Yeah, it's because of the different repeat count, 127 vs 128 (2nd char `n` vs `o`).

**Comment by JoryHogeveen** [comment]
> So implementing the button dimming codes does not make any sense as I don't think there is a way to implment this in HA.

Agreed, no point for such buttons.

> This would be an option via another remote ID, we would have to test for remote IDs also to see which ones support this.

Check!

>works for BTN1-9
ID is between 16399 and 32767
ID binary value to have odd number of 1's
ID binary value to have at least 5 1's

Found this: https://forum.arduino.cc/index.php?topic=153525.165#msg_3607041
> > _count the "1"
if the number of  "1"  is an odd number  the code is for the touch remotes
if the number of  "1"  is an even number  the code is for  4 button remotes_

--
> Yeah, it's because of the different repeat count, 127 vs 128 (2nd char n vs o).

Check! Looked at the tyjtyj script but didn't find any repeat count number in there.

**Comment by kind3r** [comment]
> Check! Looked at the tyjtyj script but didn't find any repeat count number in there.

It's the second byte of the header see here: https://github.com/kind3r/livolo-rf-codes/blob/7b5dc4b062ece6ccd79c1d65cfadebbd0258f1e4/src/broadlink.js#L31

He uses 80 (decimal 128), I defaulted to 127 for some reason :) but then switched to 200 to be more reliable in my ON / OFF scenario. This is atually part of the BroadLink protocol, how many times to repeat the code that you sent.
